### ISSUE TITLE
Profiling crashes Zing JVM

### ISSUE THREAD

**Issue by justinas-dabravolskas** [jvm-profiling-tools/async-profiler#256]
Hi,
sometimes profiling Zing causes JVM crashes. Partial hs_err:
\# An unexpected error has been detected by Java Runtime Environment:
\#
\#  Segmentation fault (0xb) at pc=0x7f31a5201ea6, pid=27120, tid=29784
\#
\# Java VM: Zing 64-Bit Tiered VM (11.0.4-zing_19.09.0.0-b4-product-linux-X86_64, mixed mode)
\# Problematic frame:
\# V  [libjvm.so+0xa78ea6]  JvmtiEnvBase::get_stack_trace(JavaThread*, int, int, _jvmtiFrameInfo*, int*)+0x576

---------------  T H R E A D  ---------------

Current thread (0x44002c200000):  JavaThread "XXX" daemon [JVM locked by self running, polling bits: NONE , id=29784, stack(0x7f2f4c7c5000,0x7f2f4c9c5000), java prio=5, os prio=0, sched=SCHED_OTHER]

siginfo:si_signo=Segmentation fault: si_errno=0, si_code=1 (SEGV_MAPERR), si_addr=0x1c

Registers:
RAX=0x0000000000000000, RBX=0x00007f31a5d053c0, RCX=0x00007f2f4c9b85b0, RDX=0x00007f2f4c9b85b0
RSP=0x00007f2f4c9b7d00, RBP=0x00007f2f4c9b7e50, RSI=0x0000000030006c8b, RDI=0x0000000000000000
R8 =0x00007f31a5ce5995, R9 =0x0000000000003350, R10=0x0000000000000028, R11=0x0000040000621a58
R12=0x00007f31a5ce5990, R13=0x00007f306c20e620, R14=0x0000040000621a70, R15=0xfffffffffffffffe
RIP=0x00007f31a5201ea6, EFL=0x0000000000010293, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x7f2f4c9b7d00)
....

RAX=0x0000000000000000 is an unknown value
RBX=0x00007f31a5d053c0: libjvm.so+(nil)
RCX=0x00007f2f4c9b85b0 is pointing into the execution stack for thread: 0x000044002c200000
RDX=0x00007f2f4c9b85b0 is pointing into the execution stack for thread: 0x000044002c200000
RSP=0x00007f2f4c9b7d00 is pointing into the execution stack for thread: 0x000044002c200000
RBP=0x00007f2f4c9b7e50 is pointing into the execution stack for thread: 0x000044002c200000
RSI=0x0000000030006c8b is at begin+75 in a stub
StubRoutines::call_stub [0x0000000030006c40, 0x0000000030006cda] (154 bytes)
RDI=0x0000000000000000 is an unknown value
R8 =0x00007f31a5ce5995: libjvm.so+(nil)
R9 =0x0000000000003350 is an unknown value
R10=0x0000000000000028 is an unknown value
R11=0x0000040000621a58 is an oop
PageNum: 0x200003 State: Allocated, Gen: Perm, Space: Small
R12=0x00007f31a5ce5990: libjvm.so+(nil)
R13=0x00007f306c20e620 is an unknown value
R14=0x0000040000621a70 is an oop
PageNum: 0x200003 State: Allocated, Gen: Perm, Space: Small
R15=0xfffffffffffffffe is an unknown value

Stack: [0x7f2f4c7c5000,0x7f2f4c9c5000],  sp=0x7f2f4c9b7d00,  free space=1995k
Native frames: (J Jn Jo=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xa78ea6]  JvmtiEnvBase::get_stack_trace(JavaThread*, int, int, _jvmtiFrameInfo*, int*)+0x576
V  [libjvm.so+0xa6bc54]  JvmtiEnv::GetStackTrace(JavaThread*, int, int, _jvmtiFrameInfo*, int*)+0xb4
C  [libasyncProfiler.so+0x182d2]  Profiler::getJavaTraceJvmti(_jvmtiFrameInfo*, ASGCT_CallFrame*, int)+0x42

CompilerOracle commands:

---------------  P R O C E S S  ---------------

VM state:not at safepoint (normal execution)

AzLocks currently owned by a thread:  ([azlock/os_lock])
[0x7f31a5d00280/0x1255fa0] VMOperationQueue_lock - owner thread: 0x440002200000
[0x7f31a5cfe8c0/0x1258cf0] Threads_lock - owner thread: 0x440001c00000
[0x7f31a5cfe780/0x1258e50] ReferencePendingList_lock - owner thread: 0x440002a00000
[0x7f31a5cfe5a0/0x12590c0] GPGC_Safepoint_lock - owner thread: 0x440001c00000
[0x7f31a5cfe1e0/0x1259510] CompileTask1_lock - owner thread: 0x440003800000

...

Regards,
Justinas

**Comment by apangin** [comment]
Is it `cpu` profiling mode?

**Comment by justinas-dabravolskas** [comment]
Yes

**Comment by apangin** [comment]
Looks like a Zing-specific issue. I committed the fix. Please check if it solves the problem.

**Comment by justinas-dabravolskas** [comment]
Hi, looks like problem is still there.  Sometimes it works for a few seconds but never managed to run it for at least 60s. 
\# (0xe0000040) at pc=(nil), pid=126494, tid=1956
\# Error: Checkpoint sync time longer than 200000 ms detected
\#
\# Java VM: Zing 64-Bit Tiered VM (11.0.4-zing_19.09.0.0-b4-product-linux-X86_64, mixed mode)
\# Problematic frame:
\# C (nil)
\#


--------------- T H R E A D ---------------

Current thread (0x440002200000): VMThread [stack: 0x7f607ebf7000,0x7f607edf7000] [id=1956]

Stack: [0x7f607ebf7000,0x7f607edf7000]
VM_Operation (0x7f607df20c90): Checkpoint, mode: no safepoint, requested by thread 0x440002c00000

**Comment by apangin** [comment]
As far as I can see from the top of the error message, it's definitely not the same problem. It's not a crash, but somewhat like a hang detected by VM Thread.

Please share the details how to reproduce the problem. I haven't seen this in my tests.

**Comment by apangin** [comment]
I'm closing the issue, as the original bug has been fixed.
Feel free to open a new one if you see other problems.
